### ISSUE TITLE
make error: ‘long double’ is not a class, struct, or union type

### ISSUE THREAD

**Issue by KeXinDING37** [wuyangf7/OPERA#1]
Thank you for your excellent work!
I encountered the following error during installation, could you please indicate the solution?
<img width="788" alt="image" src="https://github.com/wuyangf7/OPERA/assets/123853854/5ebc0a80-50bb-4eaa-a3f5-5678075c878b">
Thank you for your help and look forward to your reply！

**Comment by wuyangf7** [comment]
Hi Kexin, it indicates sth related to your boost library. Please can you check if the path for Boost library is set up properly. 
BTW, we have also provided the compiled executed file in the same folder.

**Comment by KeXinDING37** [comment]
Thank you for your quick reply and helpful suggestions, the problem has been solved. Thank you!
