### ISSUE TITLE
Two questions about OPERA

### ISSUE THREAD

**Issue by cwnag-c** [wuyangf7/OPERA#2]
Hello YangWu

Thank you for developing OPERA！

I had some questions about OPERA. First, i noticed that OPERA or SMR does not filter snps  with ambiguous strand,  could it influence the results? Second,  i found some xQTL files were  each chromosome separately，so can the stage 1 analysis be performed for each chromosome separately?  

I am extremely grateful for your assistance in resolving this issue!

Thank you,
ChaoWang

**Comment by wuyangf7** [comment]
Hi Chao,

Thank you for your interest on our software tool! 

Re 1) OPERA does not filter SNPs with ambiguous strand. But OPERA does comparison between the alleles in GWAS, xQTL and LD reference. So if a SNP has different allele information (e.g., strand) in three datasets, OPERA will remove such SNP.  

Re 2) No, the stage 1 analysis requires the genome-wide input. But in stage 2 analysis, you can run the chromosome-wide analysis to accelerate the computation. 

Hope it helps, 
Yang

**Comment by cwnag-c** [comment]
Do I need to filter out SNPs with ambiguous strand before I perform OPERA?

**Comment by wuyangf7** [comment]
Yes, it is better to filter out SNPs with ambiguous strand before the analysis.

**Comment by cwnag-c** [comment]
Thank you so much for patiently answering my questions！！！
