### ISSUE TITLE
Obtaining z-score, beta value and SE from RASQUAL output

### ISSUE THREAD

**Issue by isosceleswheel** [wuyangf7/OPERA#7]
Hello,

I have identified QTLs from chromatin accessibility (caQTL) and histone lysine 27 acetylation (hQTL) data using the [RASQUAL program](https://github.com/natsuhiko/rasqual). This program does not produce the standard beta and SE values of many of the other popular programs. Instead, it has an estimated effect size for QTLs $\pi$ that ranges from 0-1 and a $\chi^2$ statistic rather than SE. It also produces Benjamini-Hochberg corrected p-values (Q values) to indicate the significance of the QTLs.

I have come across conflicting suggestions for converting these outputs into the values needed to run OPERA or other colocalization analyses (see [here](https://github.com/natsuhiko/rasqual/issues/55)). 

My question is, are you familiar with the summary statistics from RASQUAL and do you have any suggestions for converting these to standardized inputs like beta, SE and z-score values that can be used as inputs for OPERA?

Thanks!
-David

**Comment by wuyangf7** [comment]
Hi David,

Sorry for the late reply. You can get the estimated SE = sqrt(effect size^2 / χ2 statistic). z-score = effect size / SE. 

Best regards,
Yang

**Comment by isosceleswheel** [comment]
Hi Yang,

Thanks for your reply. I have been investigating this issue and I believe I have found the answer, which differs somewhat from what you have suggested above. I have put up a [long post on this thread](https://github.com/natsuhiko/rasqual/issues/55#issuecomment-2286737201) showing my results that you might want to take a look at. Please let me know if you think this is correct.

Take care,
David

**Comment by wuyangf7** [comment]
Hi David,

It looks good to me. 
Why not just use QTLtools to run the analysis? We have provided a tutorial to convert QTLtools output to the required format. 

Best regards,
Yang

**Comment by isosceleswheel** [comment]
Thanks, Yang.

For various reasons the RASQUAL analysis is important to other elements of our work, so we will stick with the converted values from those results.
