### ISSUE TITLE
Defining the --extract-gwas-loci regions

### ISSUE THREAD

**Issue by isosceleswheel** [wuyangf7/OPERA#8]
Hi Yang,

In your documentation example for Stage 2, the variable `--extract-gwas-loci` points to a file with that defines the start and end of the region to consider for analysis. You refer to the default 2Mb regions of clumped GWAS results in this section of the documentation, but in your example file [here](https://github.com/wuyangf7/OPERA/blob/main/demo/myloci) there is an approximately 43Mb region given for chromosome 7. 

For each chromosome, should my `--extract-gwas-loci` just provide a range that includes all GWAS variants on that chromosome in my dataset? Should it include additional space on either edge? Should I run multiple iterations of Stage 2 on different 2Mb regions of each chromosome that contain GWAS variants, or is Stage 2 meant to be run on a single full chromosome just once?

If you could provide more details on exactly what the `--extract-gwas-loci` region should include, with respect to the coordinates of GWAS variants as well as xQTL variants on a given chromosome, that would be very helpful. 

Thanks!

**Comment by wuyangf7** [comment]
Hi there, 

Thank you for your interest in OPERA. Each line in the file following --extract-gwas-loci corresponds to a GWAS SNP after LD clumping or COJO analysis. Specifically, each line represents the physical position of a single SNP. OPERA will then automatically open a 2Mb window centered around that position to conduct the analysis. The two lines provided in the example files represent two independent SNPs.

Best regards,
Yang

**Comment by isosceleswheel** [comment]
Hi Yang,

I figured out this part altering referring back to the paper. I used PLINK for the clumping and I am getting much better results now. Thanks!

I have now completed my analysis and I am trying to generate a plot as in Fig. 6 from the paper. However, this link you have provided on the GitHub page is dead:

	To generate the loucs omics plot with extracted file, please see the omics SMR plot page (https://plot.cnsgenomics.com/omicsplot/).

Do you have a backup link that I can use to view this page?

Thanks, 
David

**Comment by isosceleswheel** [comment]
Thanks for the reply. I have used [PLINK](https://zzz.bwh.harvard.edu/plink/clump.shtml) for clumping and the results of OPERA are much improved. Here are some details for anyone that may find it useful:

I used an $r^2$ of 0.5 for clumping for the best results with my data, although I tried a range of $r^2$ values, starting with the recommended 0.01 in the original paper and there is not a huge difference between 0.01, 0.1 and 0.5.

I use PLINK with the following parameters for clumping, where the `plink_ref_file` is genotype data from my samples, `SNP_P_file` is a file formatted `rsid pvalue` (see PLINK docs linked above). Here is the PLINK command:

```
plink --file <plink_ref_file> --clump <SNP_P_file> --out <myout> \
      --clump-p1 5e-08 --clump-p2 0.5 --clump-r2 0.5 --clump-kb 1000
```

**Comment by wuyangf7** [comment]
The suggestion I have is that,


plink --file <plink_ref_file> --clump <SNP_P_file> --out <myout> \

      --clump-p1 5e-08 --clump-p2 5e-8 --clump-r2 0.01 --clump-kb 1000

Best regards,
Yang

From: David Murphy ***@***.***>
Date: Thursday, September 26, 2024 at 03:01
To: wuyangf7/OPERA ***@***.***>
Cc: Yang Wu ***@***.***>, Comment ***@***.***>
Subject: Re: [wuyangf7/OPERA] Defining the --extract-gwas-loci regions (Issue #8)

Thanks for the reply. I have used PLINK<https://zzz.bwh.harvard.edu/plink/clump.shtml> for clumping and the results of OPERA are much improved. Here are some details for anyone that may find it useful:

I used an $r^2$ of 0.5 for clumping for the best results with my data, although I tried a range of $r^2$ values, starting with the recommended 0.01 in the original paper and there is not a huge difference between 0.01, 0.1 and 0.5.

I use PLINK with the following parameters for clumping, where the plink_ref_file is genotype data from my samples, SNP_P_file is a file formatted rsid pvalue (see PLINK docs linked above). Here is the PLINK command:

plink --file <plink_ref_file> --clump <SNP_P_file> --out <myout> \

      --clump-p1 5e-08 --clump-p2 0.5 --clump-r2 0.5 --clump-kb 1000
