### ISSUE TITLE
Link to generate locus omics plot is dead

### ISSUE THREAD

**Issue by isosceleswheel** [wuyangf7/OPERA#9]
Hi Yang,

The following link referenced at the bottom of the README for generating plots of results is broken:  https://plot.cnsgenomics.com/omicsplot/.

Do you have a backup source for this code that you can provide for generating omics locus plots?

Thanks,
David

**Comment by wuyangf7** [comment]
Hi David,

Please find the new link below,

https://yanglab.westlake.edu.cn/software/smr/#OmicsSMRplot

Best regards,
Yang


From: David Murphy ***@***.***>
Date: Thursday, September 26, 2024 at 03:03
To: wuyangf7/OPERA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wuyangf7/OPERA] Link to generate locus omics plot is dead (Issue #9)

Hi Yang,

The following link referenced at the bottom of the README for generating plots of results is broken: https://plot.cnsgenomics.com/omicsplot/.

Do you have a backup source for this code that you can provide for generating omics locus plots?

Thanks,
David
